### ISSUE TITLE
Naming of MysqlCluster master Service

### ISSUE THREAD

**Issue by devdattakulkarni** [presslabs/mysql-operator#284]
Hey,

We are using this Operator in one of our use-cases [1]. In this use-case we have a Custom Resource for Moodle and it uses the mysql cluster created using MysqlCluster Custom Resource provided by this Operator. In this setup we bind the Moodle CR with the mysql cluster created by MysqlCluster CR through its name. The naming format is "name-of-the-MysqlCluster-CR" with  the string "-mysql-master" appended to it. You can see this in the Moodle YAML [2].

I was wondering if it will be possible to update the Operator to create the underlying master Service with only the name of the MysqlCluster Custom Resource, without "-mysql-master". The reason I ask is, we want to be able to specify only the name of MysqlCluster Custom Resource as the binding target in our Moodle Custom Resource spec. This is similar to how MysqlCluster Custom Resource currently takes just the name of Secret as one of its inputs.

By providing just the name as binding target, it becomes easier to handle creation of multiple platform stacks for our Moodle Operator.

[1] https://github.com/cloud-ark/kubeplus/tree/master/examples/moodle-with-presslabs

[2] https://github.com/cloud-ark/kubeplus/blob/master/examples/moodle-with-presslabs/namespace1/moodle1.yaml

**Comment by AMecea** [comment]
Hi @devdattakulkarni, thanks for suggestions! I don't think we can rename it because it's too alike to have name collisions. But from version `0.3.0` the service name will be `<cluster-name>-mysql`, the same for writes and for reads, because of using ProxySQL(#10).

What I recommend is to use the credentials secret as a link between the app and the MySQL Cluster. In that secret, fill the `DB_CONNECT_URL` to contains all connection details, as we do in [the cluster chart](https://github.com/presslabs/mysql-operator/blob/d5987350d204e3de5319aa8ac5580f3eb13d6faa/hack/charts/mysql-cluster/templates/secret.yaml#L16).

Also, we would like to add a new field on the cluster that lets you customize this service(e.g. name, type, port..), so you can create the service with the cluster name.

Hope this helps!
