### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'lsn'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by vishnukanth-chittayala** [presslabs/mysql-operator#485]
please help me solve this  

ERROR 1045 (28000): Access denied for user '-p'@'localhost' (using password: NO)

**Comment by AMecea** [comment]
Hi @vishnukanth-chittayala 

Where do you get this error?

**Comment by vishnukanth-chittayala** [comment]
In command prompt I got while trying to connect to MySQL for my project I
did my project in spring boot
It is not allowing me to connect to database
And not allowing me to connect me as root admin

**Comment by AMecea** [comment]
You have to let the operator create a user for you. You can do that by filling the secret with the `USER` `PASSWORD` and `DATABASE` keys as in this [example](https://github.com/presslabs/mysql-operator/blob/09db565ddb40d3a1a0e84c2753a4eeb42868a562/examples/example-cluster-secret.yaml#L11), make sure to be base64 encoded. Also, you have to create a new cluster because once the cluster is initialized the bootstrap user is ignored.

Then in your application just connect to `<cluster_name>-mysql-master` using the user and password that you've already set in the secret. 

Or using the MySQL client:
```
mysql -h <cluster_name>-mysql-master -u<user-name> -p<user-password>
```

Please let me know if this helps.

**Comment by vishnukanth-chittayala** [comment]
I tried creating new user and created a database it is running but still
not giving me permission saying access denied
Same error with finally saying yes

**Comment by AMecea** [comment]
The error says that you are not using a password. Not sure how can I help you.
Try to list MySQL users by running:
```
$ kubectl exec -it <cluster-name>-mysql-0 bash 
bash-4.2$ mysql --defaults-file=/etc/mysql/client.conf 
mysql> select * from mysql.user;
```

**Comment by vishnukanth-chittayala** [comment]
I will try what you said if did not get it then I will let you know

**Comment by vishnukanth-chittayala** [comment]
Sorry I don't remember now it was long time ago

**Comment by kylezhou1992** [comment]
> The error says that you are not using a password. Not sure how can I help you. Try to list MySQL users by running:
> 
> ```
> $ kubectl exec -it <cluster-name>-mysql-0 bash 
> bash-4.2$ mysql --defaults-file=/etc/mysql/client.conf 
> mysql> select * from mysql.user;
> ```

Then I list all the users. So I found that root and the user I created lost.
