### ISSUE TITLE
Questions on the operator

### ISSUE THREAD

**Issue by smanpathak** [presslabs/mysql-operator#63]
Forgive me for raising the PR, but cannot think of another way to do this.
* Can you elaborate on roadmap/plans for this project? How do you perceive community contributions/adoption?
* Is there a space to collaborate? Slack channels are the norm these days
* Whats a good avenue for raising feature requests?

**Comment by milero** [comment]
Hi and thank you for your interest! 
The operator is only a part of our effort in "kubernetizing" WordPress using an open approach: [https://www.presslabs.com/news/mysql-operator/](https://www.presslabs.com/news/mysql-operator/) We already use the current version in our dashboard app. 
Did you take a look at the list of open issues?
We're considering using for chat Gitter instead of Slack as it seems slightly friendlier and more open. If you want to start as of now, please feel free to open an issue right here, or even to make pull requests implementing the issues already open.
